### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by ghost** [Equanox/gotron#1]

**Comment by Equanox** [comment]
It depends on your needs. If you just need a startup project for cross platform development it can give you a first a hint how to set up the basic rampup and teardown between go and gotron.

To deploy things to multiple platforms you'll have to set up a building pipeline for both codebases and integrate the executables together. For ios it is additionally necessary to sign both applications on ios.
You also need to set up another websocket to handle the communication of your applications frontend &  backend. 

Don't expect magic. It's just very basic stuff. Be ready to set up a lot of your application stuff on top of it.

**Comment by 0x457** [comment]
Reactjs example done?

**Comment by Equanox** [comment]
I can commit it in a couple of days if it's urgent. | Edit: 15. June. 2017 Done

**Comment by hathbanger** [comment]
Huge thanks for this!!! What's the timeline looking like for executable creation?

Again, thanks for putting this together!!!!

**Comment by Equanox** [comment]
@hathbanger it took a while but finally we provide you some commands to build executables. See [PR](https://github.com/Equanox/gotron/pull/4)

**Comment by Equanox** [comment]
I'm closing this, think we've made some progress with executable creation in direction production ready.
