### ISSUE TITLE
error while executing $npm run build on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by bratekai** [Equanox/gotron#12]
I tried to resolve the issue by changing line ending in git config, however it did not help

$ npm run build

> gotron@0.0.1 build /mnt/data/Downloads/opt/opt/golang/src/go_electron
> npm run build:js

> gotron@0.0.1 build:js /mnt/data/Downloads/opt/opt/golang/src/go_electron
> cd ui/js && npm run build

> frontend@0.1.0 build /mnt/data/Downloads/opt/opt/golang/src/go_electron/ui/js
> webpack

Hash: 4b93db3183f37013989f
Version: webpack 2.7.0
Time: 671ms
                               Asset     Size  Chunks             Chunk Names
7b5fb88f12bec8143f00e21bc3222124.ttf   162 kB          [emitted]  
                           bundle.js  74.5 kB       0  [emitted]  main
   [0] ./src/app.js 356 bytes {0} [built]
   [1] ./~/base64-js/index.js 3.94 kB {0} [built]
   [2] ./~/buffer/index.js 48.6 kB {0} [built]
   [3] ./~/css-loader!./src/style.css 539 bytes {0} [built]
   [4] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
   [5] ./~/ieee754/index.js 2.06 kB {0} [built]
   [6] ./~/isarray/index.js 132 bytes {0} [built]
   [7] ./~/style-loader/addStyles.js 8.51 kB {0} [built]
   [8] ./~/style-loader/fixUrls.js 3.01 kB {0} [built]
   [9] ./src/style.css 899 bytes {0} [built]
  [10] ./src/Roboto-Light.ttf 82 bytes {0} [built]
  [11] (webpack)/buildin/global.js 509 bytes {0} [built]
  [12] multi ./src/app.js 28 bytes {0} [built]

> gotron@0.0.1 postbuild:js /mnt/data/Downloads/opt/opt/golang/src/go_electron
> cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js"

/usr/bin/env: ‘node\r’: No such file or directory

npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:js"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! gotron@0.0.1 postbuild:js: `cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the gotron@0.0.1 postbuild:js script 'cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gotron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gotron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gotron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/data/Downloads/opt/opt/golang/src/go_electron/npm-debug.log

npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gotron@0.0.1 build: `npm run build:js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gotron@0.0.1 build script 'npm run build:js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gotron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gotron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gotron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/data/Downloads/opt/opt/golang/src/go_electron/npm-debug.log

**Comment by puengel** [comment]
Hello @bratekai ,
Seems like there is a bad call

> gotron@0.0.1 postbuild:js /mnt/data/Downloads/opt/opt/golang/src/go_electron
cpy ui/js/build/. app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js"

should be like this. (note the `*.*`)

 ```
 gotron@0.0.1 postbuild:js /home/dani/go/src/gotron
> cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js"
```

Also can you please check if you followed these installation steps:
```
cd gotron
npm install
npm run build
go run .
```

instead of these:
```
cd gotron
npm run install
npm run build
go run .
```

Hope that helps.
Cheers

**Comment by bratekai** [comment]
It did not :(. 

my bad, I previously inserted build output without quotes. That is why *.* went missing. The listing is OK at the moment; exactly as I see it on my screen.

it crashes on postbuild:js. I would be grateful for solution :)

```
$ npm run build

> gotron@0.0.1 build /mnt/data/Downloads/opt/opt/golang/src/go_electron
> npm run build:js


> gotron@0.0.1 build:js /mnt/data/Downloads/opt/opt/golang/src/go_electron
> cd ui/js && npm run build


> frontend@0.1.0 build /mnt/data/Downloads/opt/opt/golang/src/go_electron/ui/js
> webpack

Hash: 4b93db3183f37013989f
Version: webpack 2.7.0
Time: 676ms
                               Asset     Size  Chunks             Chunk Names
7b5fb88f12bec8143f00e21bc3222124.ttf   162 kB          [emitted]  
                           bundle.js  74.5 kB       0  [emitted]  main
   [0] ./src/app.js 356 bytes {0} [built]
   [1] ./~/base64-js/index.js 3.94 kB {0} [built]
   [2] ./~/buffer/index.js 48.6 kB {0} [built]
   [3] ./~/css-loader!./src/style.css 539 bytes {0} [built]
   [4] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
   [5] ./~/ieee754/index.js 2.06 kB {0} [built]
   [6] ./~/isarray/index.js 132 bytes {0} [built]
   [7] ./~/style-loader/addStyles.js 8.51 kB {0} [built]
   [8] ./~/style-loader/fixUrls.js 3.01 kB {0} [built]
   [9] ./src/style.css 899 bytes {0} [built]
  [10] ./src/Roboto-Light.ttf 82 bytes {0} [built]
  [11] (webpack)/buildin/global.js 509 bytes {0} [built]
  [12] multi ./src/app.js 28 bytes {0} [built]

> gotron@0.0.1 postbuild:js /mnt/data/Downloads/opt/opt/golang/src/go_electron
> cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js" 

/usr/bin/env: ‘node\r’: No such file or directory

npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:js"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! gotron@0.0.1 postbuild:js: `cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js" `
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the gotron@0.0.1 postbuild:js script 'cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gotron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cpy ui/js/build/*.* app/assets/ && move-cli app/assets/bundle.js app/assets/js/index.js && echo "Build Ui {ui/js}, cp bundle.js to app/assets/js/index.js" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gotron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gotron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/data/Downloads/opt/opt/golang/src/go_electron/npm-debug.log

npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gotron@0.0.1 build: `npm run build:js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gotron@0.0.1 build script 'npm run build:js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gotron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gotron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gotron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/data/Downloads/opt/opt/golang/src/go_electron/npm-debug.log

```

**Comment by bratekai** [comment]
I did tried to follow

> cd gotron
> npm install
> npm run build
> go run .

it crashes on: 
> npm run build

**Comment by puengel** [comment]
I noticed you are using
>node v8.10.0
>npm  v3.5.2

Can you please try updating your node and npm version? I am using
>node v10.10.0 (you can also go for a later version)
>npm v6.4.1 (latest)

**Comment by bratekai** [comment]
hmm... I prefer to stick with LTS, at least for the moment.
Anyway I made it go away
```
$sudo apt-get install dos2unix
$cd gotron
$find . -exec dos2unix {} \;
```
It builds now :)
