### ISSUE TITLE
problems with running $go run . on Ubuntu 18.04 

### ISSUE THREAD

**Issue by bratekai** [Equanox/gotron#13]
I am trying to run 
`$ go run main.go` because `$ go run .` does not work

Anyway I am getting compilation error from Golang:
```
# command-line-arguments
./main.go:124:21: undefined: FrontendPath
```

This is coming from that line in main.go:

```
//Conditional compilatiion for dev and prod
	path, exe, args := FrontendPath()
```

Any suggestions why ?

**Comment by puengel** [comment]
That is why you should use 
> go run .

So that go takes all .go files in that directory in account.
What is the problem with
 > go run .

?

**Comment by bratekai** [comment]
I got the message:
```
$ go run .
go run: no go files listed
```

**Comment by puengel** [comment]
There may be a problem with your go runtime.
What go version are you on?
Are you able to run ```go run . ``` on other go projects?

**Comment by bratekai** [comment]
OK. It compiles. I got the violet window :):
```
$go get ./...
$go build .
$./gotron
```

**Comment by bratekai** [comment]
my go version
`go version go1.10.4 linux/amd64`

**Comment by bratekai** [comment]
Thank you very much indeed for your help and ideas :).
Over and out.
