### ISSUE TITLE
Break package github.com/puengel/copy

### ISSUE THREAD

**Issue by rafaelgfirmino** [Equanox/gotron#15]
First congratulations for the initiative!

When I using the command go mod tidy the package github.com/puengel/copy has a breaking on this repository. The github link for this repository don't exist.

**Comment by puengel** [comment]
Thanks for your attentiveness.
You are right this module is no longer used in gotron and does not exist anymore. It has been used to investigate and debug issues with copying symbolic links in macOS and has been replaced by github.com/termie/go-shutil later on.

Please have a look at #16 
This should fix your issue.

Cheers,
Puengel

**Comment by Equanox** [comment]
Resolved & Merged by #16

**Comment by rafaelgfirmino** [comment]
Thanks!
