### ISSUE TITLE
how can i replicate the example using react

### ISSUE THREAD

**Issue by saito-sv** [Equanox/gotron#29]
This is more a question. I've look into the examples using reactjs but im a bit confused on how to replicate an actual project using it. It looks like you have 2 `package.json` files one at the root and one inside each ui folder. Would be nice if this can be run independently or maybe im not understanding the setup correctly. 
Thanks lots

**Comment by saito-sv** [comment]
I guess I figured it out. Heres a boiler plate I created in case someone is looking for one. https://github.com/Marlon-Monroy/gotron-react-boilerplate

**Comment by Equanox** [comment]
Great that you figured it out yourself. This makes me think that it may be easier to understand if we  have examples for each frontend tech in a different repo, like yours. Can you polish your README a bit? So i can put a direct link to your https://github.com/Marlon-Monroy/gotron-react-boilerplate into gotrons main README.

**Comment by saito-sv** [comment]
> Great that you figured it out yourself. This makes me think that it may be easier to understand if we have examples for each frontend tech in a different repo, like yours. Can you polish your README a bit? So i can put a direct link to your https://github.com/Marlon-Monroy/gotron-react-boilerplate into gotrons main README.
I will.

**Comment by saito-sv** [comment]
@Equanox  Ive updated the `README` take a look https://github.com/Marlon-Monroy/gotron-react-boilerplate

**Comment by Equanox** [comment]
Added your project to Readme. Thx for your help :+1:
