### ISSUE TITLE
copy.Perm undefined

### ISSUE THREAD

**Issue by genelliott** [Equanox/gotron#31]
Hi There,

Looks like copy.Perm doesn't exist in the module github.com/puengel/copy.  The following error is printed out during compilation:

# github.com/Equanox/gotron
../github.com/Equanox/gotron/gotron_methods.go:122:9: undefined: copy.Perm

However copy.Copy works ok:

  if firstRun || forceInstall {
    templateDir := filepath.Join(gbwDirectory, templateApplicationDir)
    //err = copy.Perm(templateDir, gbw.AppDirectory, 0777, 0644)
    err = copy.Copy(templateDir, gbw.AppDirectory)
    errz.Fatal(err)
  }

cheers.

**Comment by puengel** [comment]
Fixed in #32
