### ISSUE TITLE
gotron-builder fails on windows

### ISSUE THREAD

**Issue by forepick** [Equanox/gotron#37]
Hello

gotron-builder failes on windows with the following error:

```
npm WARN mosaicpresentation No description
npm WARN mosaicpresentation No repository field.
npm WARN mosaicpresentation No README data
npm WARN mosaicpresentation No license field.

+ electron-builder@20.39.0
updated 1 package and audited 3259 packages in 3.517s
found 16 vulnerabilities (2 low, 10 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
1553614107 FTL home/equa/repos/gotron/cmd/gotron-builder/main.go:64 > : : exec: ".gotron-builder\\node_modules\\.bin\\electron-builder": file does not exist: exec: ".gotron-builder\\node_modules\\.bin\\electron-builder": file does not exist: : exec: ".gotron-builder\\node_modules\\.bin\\electron-builder": file does not exist: exec: ".gotron-builder\\node_modules\\.bin\\electron-builder": file does not exist
```

**Comment by puengel** [comment]
Hello @forepick 

Can you specify which parameters you used for gotron-builder?
Do you by chance have an empty .gotron-builder directory after running gotron-builder? If yes please try if the fix mentioned in #33 fixes your problem.

Thanks

**Comment by forepick** [comment]
Hi @puengel 

Thanks for the quick response. This project is a great deal for us!
On the Windows machine, I run `gotron-builder` with no extra parameters, from CMD in administrator mode.
After running this, I do get an empty .gotron-builder folder under my project.
I'll go ahead and check this fix now.

**Comment by forepick** [comment]
OK, just rebuilt gotron-builder and still the same issue.

**Comment by puengel** [comment]
Are you on branch `gotron-builder-fix`?

**Comment by forepick** [comment]
Sorry. My bad. It did resolve this problem! 
Now there is another one (Not sure if it's related):
The resulted exe file cannot run independently without the `electronjs `folder next to it. Is it a part of the same issue?

**Comment by puengel** [comment]
No this is meant to be.
Inside the electronjs folder there is everything you need for the electron fronted (including your UI folder).

**Comment by forepick** [comment]
Great! got it
Is there any way to pack a single self-contained exe file?

**Comment by puengel** [comment]
Currently not, sorry.
But this seems to be a good idea for future developments.

**Comment by forepick** [comment]
OK.
Thanks for the help!
